version: '3.8'

services:
  app:
    build:
      context: . 
    ports:
      - "5000:80"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    networks:
      - journey-network

  redis:
    image: redis:7
    container_name: journey-redis
    ports:
      - "6379:6379"
    networks:
      - journey-network

networks:
  journey-network:
